language: python
python:
    - '2.7'
install: pip install -r requirements.txt
script: python test.py

addons:
    - ssh_known_hosts: 52.1.112.110
    - postgresql: "9.3"

before_script:
    - psql -c 'create database tweets;' -U postgres

env: DATABASE_URL='postgres://postgresql@postgresql:5432/tweets'

after_success:
    - chmod 600 .travis/tweet.pem
    - mkdir -p ~/.ssh
    - cp .travis/tweet.pem ~/.ssh
    - cat .travis/host >> ~/.ssh/config
    - git remote add production dokku@52.1.112.110:tweet
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && git push production master

before_install:
    - openssl aes-256-cbc -K $encrypted_49bb85752cc6_key -iv $encrypted_49bb85752cc6_iv -in .travis/tweet.pem.enc -out .travis/tweet.pem -d
